# Generated by Django 4.1.6 on 2023-03-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
