# Generated by Django 4.1.6 on 2023-03-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_num_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='num_likes',
            new_name='likes_count',
        ),
    ]
