# Generated by Django 4.1.6 on 2023-03-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
