# Generated by Django 4.1.6 on 2023-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist_listing_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, default='https://www.yiwubazaar.com/resources/assets/images/default-product.jpg'),
        ),
    ]
